name: Haxe Checkstyle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Verify Haxe installation
        run: haxe --version

      - name: Install Checkstyle
        run: haxelib install checkstyle

      - name: Run Checkstyle
        run: haxelib run checkstyle src/
        # Replace `src/` with the path to the folder you want to check
