# This is a basic workflow to help you get started with Actions

name: Build


# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# For release builds
  workflow_call:
    inputs:
      buildFlags:
        required: false
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildLinux:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Restore Previous Cache
        id: cache-build-linux-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/
          key: cache-linux-build
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh
      - name: Compile hxcpp
        run: |
          cd ~/haxelib/hxcpp/git/tools/run
          haxe compile.hxml
          cd ..
          cd ./hxcpp
          haxe compile.hxml
          cd ../..
      - name: Compile
        run: haxelib run lime build linux -D ${{ inputs.buildFlags }}
      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-linux-build") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }

      - name: Save Current Cache
        id: cache-build-linux-save
        uses: actions/cache/save@main
        with:
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/
          key: cache-linux-build
      - name: Publish Artifact
<<<<<<< HEAD
        uses: actions/upload-artifact@main
=======
        uses: actions/upload-artifact@v3.0.0
>>>>>>> 56408d79b62ab5eeb99ee5ff647a960e5afe1f12
        with:
          name: linuxBuild
          path: export/release/linux/bin

  buildWindows:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Restore Previous Cache
        id: cache-build-windows-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          key: cache-windows-build
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > /dev/null --quiet
          .\"setup/windows.bat"
        shell: cmd
      - name: Compile hxcpp
        run: |
          cd C:/haxelib/hxcpp/git/tools/run
          haxe compile.hxml
          cd ..
          cd ./hxcpp
          haxe compile.hxml
          cd ../..
      - name: Compile
        run: haxelib run lime build windows -D ${{ inputs.buildFlags }}
      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-windows-build") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }

      - name: Save Current Cache
        id: cache-build-windows-save
        uses: actions/cache/save@main
        with:
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          key: cache-windows-build
      - name: Publish Artifact
<<<<<<< HEAD
        uses: actions/upload-artifact@main
=======
        uses: actions/upload-artifact@v3.0.0
>>>>>>> 56408d79b62ab5eeb99ee5ff647a960e5afe1f12
        with:
          name: windowsBuild
          path: export/release/windows/bin
  buildMac:
    runs-on: macos-12

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Restore Previous Cache
        id: cache-build-macos-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
          key: cache-macos-build
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh
      - name: Compile hxcpp
        run: |
          cd ~/haxelib/hxcpp/git/tools/run
          haxe compile.hxml
          cd ..
          cd ./hxcpp
          haxe compile.hxml
          cd ../..
      - name: Compile
        run: haxelib run lime build mac -D ${{ inputs.buildFlags }}
      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-macos-build") {
            				console.log('Clearing ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }

      - name: Save Current Cache
        id: cache-build-macos-save
        uses: actions/cache/save@main
        with:
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
          key: cache-macos-build
      - name: Publish Artifact
<<<<<<< HEAD
        uses: actions/upload-artifact@main
        with:
          name: macBuild
          path: export/release/macos/bin
=======
        uses: actions/upload-artifact@v3.0.0
        with:
          name: macBuild
          path: export/release/macos/bin
  buildAndroid:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.4
          
      - name: Cache haxelib path
        uses: actions/cache@v2
        with:
          path: |
            %~/haxelib%
          key: ${{ runner.os }}-android
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: '11'
        
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r15c

      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install hxcpp > /dev/null
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib install flixel-tools
          haxelib install flixel-ui 
          haxelib install flixel-addons
          haxelib install hscript
          haxelib git linc_luajit https://github.com/jigsaw-4277821/linc_luajit.git
          haxelib git extension-androidtools https://github.com/jigsaw-4277821/extension-androidtools.git   
          haxelib git extension-videoview https://github.com/jigsaw-4277821/extension-videoview.git --quiet
          haxelib list
          
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: |
          haxelib run lime setup android
          haxelib run lime build android --app-version="4.0.0-${{ github.run_id}}"
          
      - name: Publish Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
>>>>>>> 56408d79b62ab5eeb99ee5ff647a960e5afe1f12
